### ISSUE TITLE
Auto Sanctions

### ISSUE THREAD

**Issue by antkarag13** [ShadyDevelopers/Shady#22]
Ousiastika otan kapoios kanei warn enan member an kapoios member exei simplirosei px 3 warns mute, 5 warns na ginetai kick kai 9 ban. Auto tha mporouse o kathe owner tou server na to allazei meso kapoiou command i apo to dashboard. Tha itan poli xrisimo giati den tha xriazetai kapoios owner na leei stous moderators tou oti otan simplirosei kapoios enan arithmo warns na parnei kai to analogo sanction.

**Comment by Tougrel** [comment]
We are already planning on adding it as a feature on the dashboard. The reason we didn't add this on 0.4 with the new system was because it was going to be too complicated for server admins to set up it via commands 😄

**Comment by z7rwastaken** [comment]
Moved to #32.
