### ISSUE TITLE
Log Module

### ISSUE THREAD

**Issue by z7rwastaken** [ShadyDevelopers/Shady#27]
After people requesting it, we are bringing an entirely new Log Module! Moderation in a discord server is a key in success and be sure that the new Log Module will be introducing many new moderation utilities 👀

**Comment by Tougrel** [comment]
I am gonna add that server owners and administrators will be able to separate their server logs from the main server to a child server (secondary server or logs server) keeping the main server clean!

**Comment by z7rwastaken** [comment]
Yup when we say **ShadowProtector©️** is a customizable bot we mean it! Y'all will see in v0.5 & when the Dashboard comes out! May've been a *little* postponed but it's worth the time for sure 👀
