### ISSUE TITLE
Leveling system per server 

### ISSUE THREAD

**Issue by MGkillergamer007** [ShadyDevelopers/Shady#33]
I have an idea: 

You can make a command that changes the leaderboard to only the server members and the xp that the members have in the server and with another command you can disable it

**Comment by Tougrel** [comment]
Per-guild leveling system and leaderboards (commands too) are already implemented on v0.5! Thank you for the suggestion but please open a discussion next time if you want to suggest something. Issues are for bug reports and feature requests that we have approved from the discussions section!
