### ISSUE TITLE
Settings reset command

### ISSUE THREAD

**Issue by orestis119** [ShadyDevelopers/Shady#4]
Ένα νέο command με το όπιο θα μπορεί να κανει reset όλα τα settings

**Comment by Sxpherr** [comment]
Database system o

**Comment by Tougrel** [comment]
This feature is now in progress. I am not going to add this on the canary build right now because we want to add a slash command for the settings and it will take some time to create a good command handler with no errors.

Expect a reset button on the dashboard on the alpha release
