### ISSUE TITLE
Bug in leaderboard

### ISSUE THREAD

**Issue by orestis119** [ShadyDevelopers/Shady#49]
**Describe the bug**
Στο leaderboard σε κάποια άτομα που δεν έχουν καθόλου badges έχουν το box των badges 

**Screenshots**
![Screenshot_2021-11-06-20-08-46-78](https://user-images.githubusercontent.com/72334770/140621134-a3b46eda-eb44-4ab7-b0bf-f3daaabcb6e3.jpg)

**Comment by Tougrel** [comment]
Δεν είναι bug ακριβώς αυτό. Τα συγκεκριμένα άτομα έχουν badges που δεν υπάρχουν πλέον και δεν μπορεί το leaderboards να τα βρει. Δεν θα υπάρχει στο 0.5
