### ISSUE TITLE
run cmd on message edit 

### ISSUE THREAD

**Issue by orestis119** [ShadyDevelopers/Shady#7]
Αν κάποιο μήνυμα γίνει edit και είναι cmd να τρέχει κανονικά το command 

Ξέρω το έχω κάνει και στο discord αλλά είπα να το κάνω και εδώ 😛

**Comment by Tougrel** [comment]
Not gonna work on this for this patch. Wait for the 0.6 ;)

Leave this open for discussion.

**Comment by antkarag13** [comment]
Εγώ απλά εχω βάλει στο event messageUpdate ένα: client.emit("message", newMessage);

**Comment by Tougrel** [comment]
> Εγώ απλά έχω βάλει στο event messageUpdate ένα: client.emit("message", newMessage);

Δεν θα ήτανε καθόλου κακή ιδέα αυτό. Το πρόβλημα είναι ότι όσες φορές κάναμε run το message update event μας έβγαζε error στο old ή new message (τις περισσότερες φορές) κάτι που δεν μπορώ να καταλάβω. Θα πάρουμε τον χρόνο μας με αυτό το request για να δούμε αν θα γίνει καμία αλλαγή στην v13 του discordjs και θα δούμε τα docs για να το βάλουμε στο patch 0.6 όπως ανέφερα παραπάνω.

*Αν και πιστεύω ότι δεν θα χρειαστεί γιατί slash commands*

**Comment by Tougrel** [comment]
Discontinued due to Privileged Intents changes coming soon in 2022 and us moving to slash commands!
